force-app/main/default/objects/Eledo_Connection_Setting__mdt/Eledo_Connection_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Eledo Connection Setting</label>
    <pluralLabel>Eledo Connection Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Eledo_Connection_Setting__mdt/fields/Api_Key__c.field-meta.xml
<CustomField>
    <fullName>Api_Key__c</fullName>
    <description>Eledo API key.</description>
    <inlineHelpText>API key from your Eledo Account, that can be found on Eledo portal.</inlineHelpText>
    <label>Api Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Eledo_Connection_Setting__mdt/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>Eledo service endpoint.</description>
    <inlineHelpText>&quot;https://eledo.online/api/RESTv1/&quot;. Check for latest version on Eledo portal.</inlineHelpText>
    <label>Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eledo_Template__c/Eledo_Template__c.object-meta.xml
<CustomObject>
    <label>Eledo Template</label>
    <nameField>
        <label>Eledo Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eledo Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Eledo_Template__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <description>Used to filter available Eledo_Template__c&apos;s in EledoGeneratePDF lwc.</description>
    <inlineHelpText>Required for Template selection filtering on GeneratePDF component, which can be placed on different sObject record pages.</inlineHelpText>
    <label>Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eledo_Template__c/fields/SOQL__c.field-meta.xml
<CustomField>
    <fullName>SOQL__c</fullName>
    <description>Query used to retrieve specific data used for this Eledo Template configuration, when sending data to Eledo PDF Generator.</description>
    <inlineHelpText>Query used to retrieve specific data used for this Eledo Template configuration, when sending data to Eledo PDF Generator.</inlineHelpText>
    <label>SOQL</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Eledo_Template__c/fields/Template_ID__c.field-meta.xml
<CustomField>
    <fullName>Template_ID__c</fullName>
    <description>Template ID in Eledo service.</description>
    <externalId>true</externalId>
    <inlineHelpText>Currently there is only one configuration per template allowed. If you try to add more configurations to the same template, you will get &apos;Error Creating Record&apos;.</inlineHelpText>
    <label>Template ID</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/EledoAPI.cls
public with sharing class EledoAPI {
    @TestVisible
    private static Eledo_Connection_Setting__mdt testSetting;

    private static Eledo_Connection_Setting__mdt getEndpoint() {
        if (Test.isRunningTest()) {
            return testSetting;
        } else {
            return Eledo_Connection_Setting__mdt.getAll().values()[0];
        }
    }

    private static Eledo_Template__c getTemplate(String templateName) {
        Eledo_Template__c template = [
            SELECT Name, Object__c, SOQL__c, Template_ID__c
            FROM Eledo_Template__c
            WHERE Name = :templateName
        ][0];
        return template;
    }

    @SuppressWarnings('PMD.ApexSOQLInjection')
    private static String getData(Id recordId, Eledo_Template__c template) {
        sObject dataObject = Database.query(
            template.SOQL__c +
            ' WHERE Id = \'' +
            recordId +
            '\''
        );
        return JSON.serialize(dataObject);
    }

    private static HTTPResponse getPDF(
        Eledo_Connection_Setting__mdt endpoint,
        String data,
        String templateId
    ) {
        HTTP h = new HTTP();
        HTTPRequest req = new HTTPRequest();
        req.setEndpoint(endpoint.Endpoint__c + 'Generate');
        req.setMethod('GET');
        req.setHeader('Api-Key', endpoint.Api_Key__c);
        req.setHeader('Content-Type', 'application/json');
        req.setBody(
            '{\r\n\"templateId\":\"' +
            templateId +
            '\",\"file\":' +
            data +
            '}'
        );
        HTTPResponse res = h.send(req);
        return res;
    }

    @SuppressWarnings('PMD.ApexCRUDViolation')
    @AuraEnabled
    public static void generatePDF(Id recordId, String templateName) {
        try {
            Eledo_Template__c template = getTemplate(templateName);
            Eledo_Connection_Setting__mdt endpoint = getEndpoint();
            String data = getData(recordId, template);
            HTTPResponse res = getPDF(endpoint, data, template.Template_ID__c);
            if (res.getStatusCode() == 200) {
                Attachment attachment = new Attachment();
                attachment.Body = res.getBodyAsBlob();
                attachment.Name = template.Name + '.pdf';
                attachment.IsPrivate = false;
                attachment.ParentId = recordId;
                insert attachment;
            } else {
                //throw error status code response to frontend
                throw new CalloutException(res.getBody());
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static String getTemplates() {
        Eledo_Connection_Setting__mdt endpoint;
        try {
            endpoint = getEndpoint();
        } catch (ListException e) {
            throw new AuraHandledException(
                'Eledo Connection Settings custom metadata type not set. You will not be able to select a template from Eledo.'
            );
        }

        HTTP h = new HTTP();
        HTTPRequest req = new HTTPRequest();
        req.setEndpoint(endpoint.Endpoint__c + 'List?scope=Mine');
        req.setMethod('GET');
        req.setHeader('Api-Key', endpoint.Api_Key__c);
        req.setHeader('Content-Type', 'application/json');
        HTTPResponse res = h.send(req);
        if (res.getStatusCode() == 200) {
            return res.getBody();
        } else {
            //throw error status code response to frontend
            throw new AuraHandledException(res.getBody());
        }
    }
}