force-app/main/default/objects/Eledo_Connection_Setting__mdt/Eledo_Connection_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Eledo Connection Setting</label>
    <pluralLabel>Eledo Connection Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Eledo_Connection_Setting__mdt/fields/Api_Key__c.field-meta.xml
<CustomField>
    <fullName>Api_Key__c</fullName>
    <description>Eledo API key.</description>
    <inlineHelpText>API key from your Eledo Account, that can be found on Eledo portal.</inlineHelpText>
    <label>Api Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Eledo_Connection_Setting__mdt/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>Eledo service endpoint.</description>
    <inlineHelpText>&quot;https://eledo.online/api/RESTv1/&quot;. Check for latest version on Eledo portal.</inlineHelpText>
    <label>Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eledo_Template__c/Eledo_Template__c.object-meta.xml
<CustomObject>
    <label>Eledo Template</label>
    <nameField>
        <label>Eledo Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eledo Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Eledo_Template__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <description>Used to filter available Eledo_Template__c&apos;s in EledoGeneratePDF lwc.</description>
    <inlineHelpText>Required for Template selection filtering on GeneratePDF component, which can be placed on different sObject record pages.</inlineHelpText>
    <label>Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eledo_Template__c/fields/SOQL__c.field-meta.xml
<CustomField>
    <fullName>SOQL__c</fullName>
    <description>Query used to retrieve specific data used for this Eledo Template configuration, when sending data to Eledo PDF Generator.</description>
    <inlineHelpText>Query used to retrieve specific data used for this Eledo Template configuration, when sending data to Eledo PDF Generator.</inlineHelpText>
    <label>SOQL</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Eledo_Template__c/fields/Template_ID__c.field-meta.xml
<CustomField>
    <fullName>Template_ID__c</fullName>
    <description>Template ID in Eledo service.</description>
    <externalId>true</externalId>
    <inlineHelpText>Currently there is only one configuration per template allowed. If you try to add more configurations to the same template, you will get &apos;Error Creating Record&apos;.</inlineHelpText>
    <label>Template ID</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/EledoTestDataFactory.cls
@isTest
public class EledoTestDataFactory {
    public static List<Eledo_Template__c> createTemplates(
        Integer numTemplates,
        String sObjName
    ) {
        List<Eledo_Template__c> templates = new List<Eledo_Template__c>();

        for (Integer i = 0; i < numTemplates; i++) {
            Eledo_Template__c t = new Eledo_Template__c(
                Name = 'TestTemplate' + i,
                Object__c = sObjName,
                Template_ID__c = 'TestTemplateId' + i,
                SOQL__c = 'SELECT Id FROM ' + sObjName
            );
            templates.add(t);
        }
        insert templates;
        return templates;
    }

    public static Eledo_Connection_Setting__mdt createEledoConnectionSettings() {
        return new Eledo_Connection_Setting__mdt(
            MasterLabel = 'testLabel',
            DeveloperName = 'testName',
            Api_Key__c = 'testKey',
            Endpoint__c = 'testEndpoint'
        );
    }

    public static Account createAccount() {
        Account a = new Account(Name = 'TestAccount');
        insert a;
        return a;
    }

    public class EledoCalloutSuccessMock implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{"example":"test"}');
            res.setStatusCode(200);
            return res;
        }
    }

    public class EledoCalloutFailureMock implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{"example":"test"}');
            res.setStatusCode(500);
            return res;
        }
    }
}