force-app/main/default/objects/Eledo_Template__c/Eledo_Template__c.object-meta.xml
<CustomObject>
    <label>Eledo Template</label>
    <nameField>
        <label>Eledo Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eledo Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Eledo_Template__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <description>Used to filter available Eledo_Template__c&apos;s in EledoGeneratePDF lwc.</description>
    <inlineHelpText>Required for Template selection filtering on GeneratePDF component, which can be placed on different sObject record pages.</inlineHelpText>
    <label>Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eledo_Template__c/fields/SOQL__c.field-meta.xml
<CustomField>
    <fullName>SOQL__c</fullName>
    <description>Query used to retrieve specific data used for this Eledo Template configuration, when sending data to Eledo PDF Generator.</description>
    <inlineHelpText>Query used to retrieve specific data used for this Eledo Template configuration, when sending data to Eledo PDF Generator.</inlineHelpText>
    <label>SOQL</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Eledo_Template__c/fields/Template_ID__c.field-meta.xml
<CustomField>
    <fullName>Template_ID__c</fullName>
    <description>Template ID in Eledo service.</description>
    <externalId>true</externalId>
    <inlineHelpText>Currently there is only one configuration per template allowed. If you try to add more configurations to the same template, you will get &apos;Error Creating Record&apos;.</inlineHelpText>
    <label>Template ID</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/EledoTemplatesController.cls
public with sharing class EledoTemplatesController {
    @AuraEnabled(cacheable=true)
    public static List<String> getObjects() {
        List<String> objectList = new List<String>();
        for (
            Schema.SObjectType objectType : Schema.getGlobalDescribe().Values()
        ) {
            objectList.add(String.valueOf(objectType));
        }
        objectList.sort();
        return objectList;
    }

    @SuppressWarnings('PMD.ApexSOQLInjection')
    @AuraEnabled
    public static void validateSoql(String query) {
        try {
            Database.query(query + ' LIMIT 0');
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @SuppressWarnings('PMD.ApexCrudViolation')
    @AuraEnabled
    public static Eledo_Template__c getTemplate(String recordId) {
        try {
            return [
                SELECT Name, Object__c, SOQL__c, Template_ID__c
                FROM Eledo_Template__c
                WHERE Id = :recordId
            ];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}